### ISSUE TITLE
Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by panyayan311** [wbelk/apihelper-for-shopify-docs#1]
I'm testing Shopify discount code on Google console.
but  got an error 
`Cannot read property 'extend' of undefined`
can you help me?

```
ar options = {
  vendor: 'shopify-discount',
  action: 'discount',
  code: {
    text: 'coconut', 
    append_unique_numbers: true
  },
  price_rule_id: 675072933963
}
wb_apihelper(options, function(err, res){
  if ( err ) return alert(res.message)
  console.log(res)
})
```

**Comment by clarkewing** [comment]
I'm getting the same issue. Has anyone found a solve?

**Comment by wbelk** [comment]
Yes I think there is a race condition with jquery not being loading in time with our script. I am updating and will let you know asap. Thanks for bringing it to my attention.

**Comment by wbelk** [comment]
@clarkewing this should be resolved. Please let me know you still have the issue.

**Comment by clarkewing** [comment]
Hi @wbelk 
Unfortunately I'm now getting a new error.
<img width="548" alt="Screen Shot 2020-08-03 at 22 29 36" src="https://user-images.githubusercontent.com/7689302/89229501-6f4a9600-d5d9-11ea-955d-dd852d442029.png">

**Comment by wbelk** [comment]
@clarkewing ok I think I have you covered now. Looks ok for you? I checked your site as well and seems ok to my eye.

May I ask are you doing anything special with your jquery load? I notice that you have two jqueries load before my script, one from afterpay and one from the Shopify Product Reviews app, could there be an event handler that prevents something from executing until dom loaded and ready? Usually $ should be available immediately after jquery is loaded.

**Comment by clarkewing** [comment]
We're actually trying to drop jQuery with our upcoming theme. Reading through the code, I realized it was essentially just sending a GET request to a specific endpoint and we're now just submitting an Ajax request directly to it bypassing the injected JS file.
@wbelk see my email for more specifics regarding our site.

**Comment by wbelk** [comment]
Great thanks, I'm closing this issue now
